library/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get '/authors', to: 'authors#index'
  get '/authors/:id', to: 'authors#show' , as: "author"

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

library/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

library/app/models/author.rb
class Author < ApplicationRecord
  has_many :books
  validates :rut, uniqueness: true
  before_validation :strip_name
  before_validation :capitalize_first_word
  def full_name
    "#{first_name} #{last_name}"
  end

  def strip_name
    self.first_name = first_name.strip
    self.last_name = last_name.strip
  end

  def capitalize_first_word
    self.first_name = first_name.titleize
    self.last_name = last_name.titleize
  end
end

library/app/models/book.rb
class Book < ApplicationRecord 
  belongs_to :author

  validates :title, presence: true
  validates :publication_date, uniqueness: true
end

library/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

# before_action: verify_login Esto se va a hacer mas tarde cuando necesitemos que se revise constantemente que el usuario este logueado
end

library/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show] #en un futuro para edit, destroy, update
  

# /auhors
  def index 
    @authors = Author.all ### Variable globalpara authores
  end
# /authors/id
  def show

  end

  def set_author
    @author = Author.find(params[:id])
  end
end

library/app/helpers/application_helper.rb
module ApplicationHelper
end

library/app/views/authors/index.html.erb
<h1>Autores</h1>

<ul>
  <% @authors.each do |author| %>
    <li><%=  link_to author.full_name, author_path(author.id) %></li>
  <% end %>
</ul>

library/app/views/authors/show.html.erb
<h1><%= @author.full_name %></h1>

library/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Library" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>